# <p><span style="color:blue">LAB 3 - Activity 2 - KNN</span></p>

In [8]:
data <- read.csv('/media/j/23e97447-9196-4c8e-be28-b24a49d2548e/home/jayaraj/Study/DIC/german_credit_data1.csv')

In [9]:
data

     X.  Age Sex    Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  male   2   own     NA              little            1169
2     1  22  female 2   own     little          moderate          5951
3     2  49  male   1   own     little          NA                2096
4     3  45  male   2   free    little          little            7882
5     4  53  male   2   free    little          little            4870
6     5  35  male   1   free    NA              NA                9055
7     6  53  male   2   own     quite rich      NA                2835
8     7  35  male   3   rent    little          moderate          6948
9     8  61  male   1   own     rich            NA                3059
10    9  28  male   3   own     little          moderate          5234
11   10  25  female 2   rent    little          moderate          1295
12   11  24  female 2   rent    little          little            4308
13   12  22  female 2   own     little          moderate          1567
14   13  60  male   1   own     little          little            1199
15   14  28  female 2   rent    little          little            1403
16   15  32  female 1   own     moderate        little            1282
17   16  53  male   2   own     NA              NA                2424
18   17  25  male   2   own     NA              little            8072
19   18  44  female 3   free    little          moderate         12579
20   19  31  male   2   own     quite rich      NA                3430
21   20  48  male   2   own     little          NA                2134
22   21  44  male   2   rent    quite rich      little            2647
23   22  48  male   1   rent    little          little            2241
24   23  44  male   2   own     moderate        moderate          1804
25   24  26  male   2   own     NA              NA                2069
26   25  36  male   1   own     little          little            1374
27   26  39  male   1   own     little          NA                 426
28   27  42  female 2   rent    rich            rich               409
29   28  34  male   2   own     little          moderate          2415
30   29  63  male   2   own     little          little            6836
⋮    ⋮   ⋮   ⋮      ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  male   2   own     moderate        moderate         1514
972  971 43  male   1   own     little          NA               7393
973  972 29  female 0   rent    little          little           1193
974  973 36  male   2   rent    little          little           7297
975  974 33  female 2   own     little          NA               2831
976  975 57  female 1   own     quite rich      rich             1258
977  976 64  female 2   own     little          moderate          753
978  977 42  male   2   own     NA              moderate         2427
979  978 47  male   1   own     little          NA               2538
980  979 25  male   2   rent    moderate        moderate         1264
981  980 49  male   2   own     little          moderate         8386
982  981 33  male   3   rent    little          NA               4844
983  982 28  female 3   own     moderate        rich             2923
984  983 26  male   2   own     little          little           8229
985  984 30  male   1   own     little          NA               2028
986  985 25  female 2   rent    little          little           1433
987  986 33  male   2   own     little          rich             6289
988  987 64  female 2   own     moderate        NA               1409
989  988 29  male   3   free    little          little           6579
990  989 48  male   1   own     little          moderate         1743
991  990 37  male   1   own     NA              NA               3565
992  991 34  male   1   own     moderate        NA               1569
993  992 23  male   1   rent    NA              little           1936
994  993 30  male   3   own     little          little           3959
995  994 50  male   2   own     NA              NA               2390
996  995 31  female 1   own     little          NA               1736
997  996 40  male   3   own     little          little           3857
998  997 38  male   2   own     little          NA                804
999  998 23  male   2   free    little          little           1845
1000 999 27  male   2   own     moderate        moderate         4576
     Duration Purpose             Credit.Risks
1     6       radio/TV            1
2    48       radio/TV            2
3    12       education           1
4    42       furniture/equipment 1
5    24       car                 2
6    36       education           1
7    24       furniture/equipment 1
8    36       car                 1
9    12       radio/TV            1
10   30       car                 2
11   12       car                 2
12   48       business            2
13   12       radio/TV            1
14   24       car                 2
15   15       car                 1
16   24       radio/TV            2
17   24       radio/TV            1
18   30       business            1
19   24       car                 2
20   24       radio/TV            1
21    9       car                 1
22    6       radio/TV            1
23   10       car                 1
24   12       car                 1
25   10       furniture/equipment 1
26    6       furniture/equipment 1
27    6       radio/TV            1
28   12       radio/TV            1
29    7       radio/TV            1
30   60       business            2
⋮    ⋮        ⋮                   ⋮
971  15       repairs             1
972  24       car                 1
973  24       car                 2
974  60       business            2
975  30       radio/TV            1
976  24       radio/TV            1
977   6       radio/TV            1
978  18       business            1
979  24       car                 2
980  15       car                 2
981  30       furniture/equipment 2
982  48       business            2
983  21       car                 1
984  36       car                 2
985  24       furniture/equipment 1
986  15       furniture/equipment 1
987  42       business            1
988  13       radio/TV            1
989  24       car                 1
990  24       radio/TV            1
991  12       education           1
992  15       radio/TV            1
993  18       radio/TV            1
994  36       furniture/equipment 1
995  12       car                 1
996  12       furniture/equipment 1
997  30       car                 1
998  12       radio/TV            1
999  45       radio/TV            2
1000 45       car                 1

In [10]:
library(class)

# <p><span style="color:black"> Only the columns that contain numerical data are considered for the training process. <br> <br>The columns that contained numerical data are normalised to ensure that only a few variables do not dominate in the knn finding process.<br><br> Normalisation in done in such a way that all the columns contained values from 0-1</span></p>

In [11]:
max_job <- max(data$Job, na.rm = TRUE)
min_job <- min(data$Job, na.rm = TRUE)
normalized_job = (data$Job-min_job)/(max_job-min_job)

max_Age <- max(data$Age, na.rm = TRUE)
min_Age <- min(data$Age, na.rm = TRUE)
normalized_age = (data$Age-min_Age)/(max_Age-min_Age)

max_cred_amt <- max(data$Credit.amount, na.rm = TRUE)
min_cred_amt <- min(data$Credit.amount, na.rm = TRUE)
normalized_cred_amt = (data$Credit.amount-min_cred_amt)/(max_cred_amt-min_cred_amt)

max_duration <- max(data$Duration, na.rm = TRUE)
min_duration <- min(data$Duration, na.rm = TRUE)
normalized_duration = (data$Duration-min_duration)/(max_duration-min_duration)

In [12]:
# normalized_data <- cbind(normalized_age,normalized_job)
normalized_data <- cbind(normalized_age,normalized_job,normalized_cred_amt,normalized_duration)

In [13]:
normalized_data

      normalized_age normalized_job normalized_cred_amt normalized_duration
 [1,] 0.85714286     0.6666667      0.050566744         0.02941176
 [2,] 0.05357143     0.6666667      0.313689887         0.64705882
 [3,] 0.53571429     0.3333333      0.101573677         0.11764706
 [4,] 0.46428571     0.6666667      0.419940574         0.55882353
 [5,] 0.60714286     0.6666667      0.254209310         0.29411765
 [6,] 0.28571429     0.3333333      0.484483328         0.47058824
 [7,] 0.60714286     0.6666667      0.142236162         0.29411765
 [8,] 0.28571429     1.0000000      0.368548476         0.47058824
 [9,] 0.75000000     0.3333333      0.154561461         0.11764706
[10,] 0.16071429     1.0000000      0.274237922         0.38235294
[11,] 0.10714286     0.6666667      0.057499725         0.11764706
[12,] 0.08928571     0.6666667      0.223286013         0.64705882
[13,] 0.05357143     0.6666667      0.072466160         0.11764706
[14,] 0.73214286     0.3333333      0.052217454         0.29411765
[15,] 0.16071429     0.6666667      0.063442280         0.16176471
[16,] 0.23214286     0.3333333      0.056784417         0.29411765
[17,] 0.60714286     0.6666667      0.119621437         0.29411765
[18,] 0.10714286     0.6666667      0.430395070         0.38235294
[19,] 0.44642857     1.0000000      0.678386706         0.29411765
[20,] 0.21428571     0.6666667      0.174975239         0.29411765
[21,] 0.51785714     0.6666667      0.103664576         0.07352941
[22,] 0.44642857     0.6666667      0.131891713         0.02941176
[23,] 0.51785714     0.3333333      0.109552107         0.08823529
[24,] 0.44642857     0.6666667      0.085506768         0.11764706
[25,] 0.12500000     0.6666667      0.100088038         0.08823529
[26,] 0.30357143     0.3333333      0.061846594         0.02941176
[27,] 0.35714286     0.3333333      0.009684164         0.02941176
[28,] 0.41071429     0.6666667      0.008748762         0.11764706
[29,] 0.26785714     0.6666667      0.119126224         0.04411765
[30,] 0.78571429     0.6666667      0.362385826         0.82352941
[31,] ⋮              ⋮              ⋮                   ⋮
[32,] 0.05357143     0.6666667      0.06954991          0.16176471
[33,] 0.42857143     0.3333333      0.39303400          0.29411765
[34,] 0.17857143     0.0000000      0.05188731          0.29411765
[35,] 0.30357143     0.6666667      0.38775173          0.82352941
[36,] 0.25000000     0.6666667      0.14201607          0.38235294
[37,] 0.67857143     0.3333333      0.05546385          0.29411765
[38,] 0.80357143     0.6666667      0.02767690          0.02941176
[39,] 0.41071429     0.6666667      0.11978651          0.20588235
[40,] 0.50000000     0.3333333      0.12589413          0.29411765
[41,] 0.10714286     0.6666667      0.05579399          0.16176471
[42,] 0.53571429     0.6666667      0.44767250          0.38235294
[43,] 0.25000000     1.0000000      0.25277869          0.64705882
[44,] 0.16071429     1.0000000      0.14707824          0.25000000
[45,] 0.12500000     0.6666667      0.43903378          0.47058824
[46,] 0.19642857     0.3333333      0.09783207          0.29411765
[47,] 0.10714286     0.6666667      0.06509299          0.16176471
[48,] 0.25000000     0.6666667      0.33228788          0.55882353
[49,] 0.80357143     0.6666667      0.06377242          0.13235294
[50,] 0.17857143     1.0000000      0.34824475          0.29411765
[51,] 0.51785714     0.3333333      0.08215032          0.29411765
[52,] 0.32142857     0.3333333      0.18240343          0.11764706
[53,] 0.26785714     0.3333333      0.07257621          0.16176471
[54,] 0.07142857     0.3333333      0.09276989          0.20588235
[55,] 0.19642857     1.0000000      0.20408276          0.47058824
[56,] 0.55357143     0.6666667      0.11775063          0.11764706
[57,] 0.21428571     0.3333333      0.08176516          0.11764706
[58,] 0.37500000     1.0000000      0.19847034          0.38235294
[59,] 0.33928571     0.6666667      0.03048311          0.11764706
[60,] 0.07142857     0.6666667      0.08776274          0.60294118
[61,] 0.14285714     0.6666667      0.23803235          0.60294118

# <p><span style="color:black"> Miscalculation error rate is calculated for different values of k and with different ratios of training and test data.</span></p>

In [18]:
results = data.frame()

In [19]:
for (k in 1:20) {
    
#     print(k)
    col_num=2
    results[k,1] = k
    for (j in 6:8){
        
        #The percentage of data to be taken as train/test is taken from for loop.
        len_train <- ((10*j)/100)*nrow(normalized_data)
        tot <- nrow(normalized_data)
        len_test <- tot - len_train
       
        #Splitting the data into train and test as per the percentage.
        normalized_data_train <- normalized_data[0:len_train,]
        normalized_data_test <- normalized_data[(len_train+1):tot,]
        cl_train <- data[0:len_train,]$Credit.Risks
        cl_test <- data[(len_train+1):tot,]$Credit.Risks
        
        #Applying the knn function.
        predicted.labels <- knn(normalized_data_train, normalized_data_test, cl_train, k)

        #Calculating the misclassification rate.
        num.incorrect.labels <- sum(predicted.labels != cl_test)
        misclassification.rate <- num.incorrect.labels / len_test
        misclassification.rate
        
        #Forming the results dataframe.
        results[k,col_num]=misclassification.rate
        col_num = col_num+1
    }
    
}
colnames(results) <- c("k","60% Train Set","70% Train Set","80% Train Set")
results

   k  60% Train Set 70% Train Set 80% Train Set
1   1 0.3575        0.3666667     0.400
2   2 0.3900        0.3966667     0.445
3   3 0.3650        0.3533333     0.355
4   4 0.3675        0.3866667     0.345
5   5 0.3450        0.3533333     0.335
6   6 0.3250        0.3400000     0.345
7   7 0.3225        0.3233333     0.320
8   8 0.3250        0.3333333     0.320
9   9 0.3225        0.3266667     0.300
10 10 0.3175        0.3266667     0.320
11 11 0.3200        0.3300000     0.300
12 12 0.2975        0.3166667     0.295
13 13 0.3150        0.3100000     0.295
14 14 0.3075        0.3033333     0.310
15 15 0.3225        0.3066667     0.300
16 16 0.3275        0.3166667     0.300
17 17 0.3200        0.3066667     0.310
18 18 0.3075        0.3100000     0.315
19 19 0.3150        0.3100000     0.290
20 20 0.3150        0.3033333     0.295

In [ ]:
var(results[1:5,2])
var(results[15:20,2])

# <p><span style="color:blue">K has a property that, smaller k's get more influenced by the noise in the data and larger k's tend to take more computation time. This property is verified using the results of var function which is applied to values obtained from low k's and high k's  </span></p>

# <p><span style="color:blue">Also, larger sets of training data leads to overfitting which leads to lesser miscalculation rates. </span></p>

In [ ]:
for (k in 1:20) {
    
    print(k)
    col_num=2
    results[k,1] = k
    for (j in 6:8){
        
        len_train <- ((10*j)/100)*nrow(normalized_data)
        tot <- nrow(normalized_data)
        len_test <- tot - len_train
       
        normalized_data_train <- normalized_data[0:len_train,]
        normalized_data_test <- normalized_data[(len_train+1):tot,]
        cl_train <- data[0:len_train,]$Credit.Risks
        cl_test <- data[(len_train+1):tot,]$Credit.Risks
        
        predicted.labels <- knn(normalized_data_train, normalized_data_test, cl_train, k)

        num.incorrect.labels <- sum(predicted.labels != cl_test)
        misclassification.rate <- num.incorrect.labels / len_test
        misclassification.rate
        
        results[k,col_num]=misclassification.rate
        col_num = col_num+1
    }
    
}
colnames(results) <- c("k","60% Train Set","70% Train Set","80% Train Set")
results

In [ ]:
for (k in 1:20) {
    
    print(k)
    col_num=2
    results[k,1] = k
    for (j in 6:8){
        
        len_train <- ((10*j)/100)*nrow(normalized_data)
        tot <- nrow(normalized_data)
        len_test <- tot - len_train
       
        normalized_data_train <- normalized_data[0:len_train,]
        normalized_data_test <- normalized_data[(len_train+1):tot,]
        cl_train <- data[0:len_train,]$Credit.Risks
        cl_test <- data[(len_train+1):tot,]$Credit.Risks
        
        predicted.labels <- knn(normalized_data_train, normalized_data_test, cl_train, k)

        num.incorrect.labels <- sum(predicted.labels != cl_test)
        misclassification.rate <- num.incorrect.labels / len_test
        misclassification.rate
        
        results[k,col_num]=misclassification.rate
        col_num = col_num+1
    }
    
}
colnames(results) <- c("k","60% Train Set","70% Train Set","80% Train Set")
results